### ISSUE TITLE
What is JWT?

### ISSUE THREAD

**Issue by KyKyRu3Ka** [milutinke/sqcp#11]
What is JWT in config?

**Comment by milutinke** [comment]
> What is JWT in config?

Json Web Token (JWT) is a token format that is used for authentication and authorization on the modern web, with RESTFull services, you don't need to know technical details, here it is used for authentication.
In the configuration file, you have the section for JWT, there is a field for JWT secret, that is basically a secret that is used to sign and encrypt JWT tokens.
You should set it to some random long string, don't leave the default, as for the rest of JWT settings you can ignore them, they're specific for people who want different signing and encryption algorithms.
Sorry for the late reply.
