### ISSUE TITLE
Sucessfull install - login not possible

### ISSUE THREAD

**Issue by Maximator98** [milutinke/sqcp#16]
Hello,

the installation was ended up sucessfully.

I see the login aswell, but after login i recive the messages "Unable to connect to the server!".

![grafik](https://github.com/milutinke/sqcp/assets/84685425/8d028636-cca7-49e3-b1e6-776e2c752152)

![grafik](https://github.com/milutinke/sqcp/assets/84685425/bcb9033d-4656-440c-a682-ece6908741c4)

**Comment by DarkShyMW** [comment]
How you fix it?

**Comment by Maximator98** [comment]
Hi!

i just build an nginx config:

```
server {
    listen 80;
    server_name your.domain.de;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

```
