### ISSUE TITLE
[Minor] Hard coded data oversight

### ISSUE THREAD

**Issue by Steezycoding** [milutinke/sqcp#2]
Hey there!

I found a minor oversight in your code. But it can be very annoying for communities using your app.

**Location**: ./backend/Routes/v1/Api_Server.js
**Lines**: 391, 438, 560
**Issue**: the formatted strings contain this hard coded value -> "Unbans/Complaints: ***discord.link/bsf***"

All the players banned/kicked by your app will go to your Discord to argue, regardless the server they got ban.

Great job though!
Hoping you're still active on this repo :)

**Comment by milutinke** [comment]
Thanks for noticing it.
That discord is dead, but I'm gonna remove the reference anyways.

Edit: Resolved
