### ISSUE TITLE
remote admin list - bans

### ISSUE THREAD

**Issue by anklav24** [milutinke/sqcp#9]
Hi, can you explain please why harmful players can connect to the server right after ban?
Have you solved this problem?
I use remote admin list with sqcp.

**Comment by milutinke** [comment]
> Hi, can you explain please why harmful players can connect to the server right after ban? Have you solved this problem? I use remote admin list with sqcp.

There needs to be a map change for the server to load the new bans from the remote list, it is how the Squad server operates, nothing we can do about it, other than just kicking them over and over until the map has been changed.
A makeshift solution could be that you make a Squad JS plugin that takes in the ban list and auto kicks people from it if they're online, but that requires programming knowledge.

**Comment by anklav24** [comment]
Thank you, I did not think about this approach 👍

**Comment by milutinke** [comment]
I noted this problem, I'll add the above mentioned solution when implementing the new SQCP.
Thank your for sharing it with me.

**Comment by anklav24** [comment]
Btw, is there a way to increase time or maybe cache users on the Disconnected Players tab?
My admins wanted to ban cheaters after e.g. after two hours, of course there are no leads to that cheaters.

**Comment by milutinke** [comment]
> Btw, is there a way to increase time or maybe cache users on the Disconnected Players tab? My admins wanted to ban cheaters after e.g. after two hours, of course there are no leads to that cheaters.

You can't increase the time because it sources the list directly from the server, the server keeps a record for 15 minutes.
However you change it in the code to save it somewhere for a longer time and then display the saved version.
in a new version of SQCP there will be the player database and history tracking so you'll be able to ban them if they're offline.

**Comment by anklav24** [comment]
Cool, I'm not so good at JS, but maybe I can help with those two things?

**Comment by milutinke** [comment]
> Cool, I'm not so good at JS, but maybe I can help with those two things?

I might create it in .NET instead of JS this time, haven't decided yet.
